### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LMOlivera** [LiamPrett/Portfolio2#1]
Your portfolio looks amazing so far. Why don't you try to add a smooth scroll animation? It would make it perfect.

**Comment by LiamPrett** [comment]
Apologies that this comment is so late. I had abandoned the project due to lack of time. The smooth transition was there, however the script I was using was expecting HTTPS, but I had coded HTTP and github didnt like it. If you go to my portfolio now, you will see the smooth transition :) 

Slowly but surely this will be updated, so if you have any other suggestions, please feel free to suggest them :)

**Comment by LMOlivera** [comment]
Looking good so far!
